runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: savant_main.app

env_variables:
  GOOGLE_CLIENT_SECRETS: 'gcloud_client_credentials.json'
  FLASK_APP: 'savant_main.py'
  FLASK_DEBUG: '1'
  PYTHONHTTPSVERIFY: 1

libraries:
- name: ssl
  version: 2.7.11